-- AgriGuard AI Seed Data
-- Multi-Crop Reference Data & Disease Knowledge Base

USE agriguard_db;

-- Insert Crops
INSERT INTO crops (id, name, scientific_name, family_name, common_diseases, generalCare, optimal_temp, optimal_ph, watering_tips, icon_url) VALUES
(1, 'Tomato', 'Solanum lycopersicum', 'Solanaceae', 'tomato_early_blight,tomato_late_blight,tomato_yellow_leaf_curl,tomato_bacterial_spot,tomato_healthy', 'Requires full sun (6-8 hours daily), fertile well-draining loam, and sturdy trellising support.', '21-29°C', '6.0-6.8', 'Deep watering at the base 2-3 times a week. Avoid wetting foliage to prevent fungal spores.', '🍅'),
(2, 'Potato', 'Solanum tuberosum', 'Solanaceae', 'potato_early_blight,potato_late_blight,potato_healthy', 'Prefers cool conditions, loose well-aerated soil rich in organic matter. Mound soil around base as stems grow.', '15-20°C', '5.0-6.0', 'Consistent moisture throughout tuber initiation. Reduce watering before harvesting to harden skins.', '🥔'),
(3, 'Chili & Bell Pepper', 'Capsicum annuum', 'Solanaceae', 'pepper_bacterial_spot,pepper_anthracnose,pepper_healthy', 'Thrives in warm, sunny spots with rich, well-draining soil. Sensitive to cold drafts and root rot.', '22-30°C', '6.2-7.0', 'Water moderately when top inch of soil feels dry. Drip irrigation is highly recommended.', '🌶️'),
(4, 'Cotton', 'Gossypium hirsutum', 'Malvaceae', 'cotton_bacterial_blight,cotton_bollworm_damage,cotton_healthy', 'Warm-season crop requiring prolonged sunshine, deep fertile sandy loam, and regulated nitrogen inputs.', '25-35°C', '5.8-7.5', 'High water demand during flowering and boll formation; minimize water during boll opening.', '🌱'),
(5, 'Corn / Maize', 'Zea mays', 'Poaceae', 'corn_northern_leaf_blight,corn_common_rust,corn_gray_leaf_spot,corn_healthy', 'Heavy feeder needing high nitrogen, full sun, and block planting for effective wind pollination.', '20-32°C', '5.8-7.0', 'Needs 1-1.5 inches of water per week, critical during silking and tasseling phases.', '🌽'),
(6, 'Apple', 'Malus domestica', 'Rosaceae', 'apple_scab,apple_black_rot,apple_cedar_rust,apple_healthy', 'Requires winter chilling hours, well-drained orchard loam, good air circulation, and annual dormant pruning.', '15-24°C', '6.0-7.0', 'Deep watering every 7-10 days for young trees. Mulch heavily around root zone.', '🍎'),
(7, 'Grape', 'Vitis vinifera', 'Vitaceae', 'grape_black_rot,grape_powdery_mildew,grape_leaf_blight,grape_healthy', 'Requires well-drained gravelly or rocky slopes, full sun exposure, and strict canopy management.', '20-30°C', '5.5-6.5', 'Deep, infrequent watering. Drip systems under trellis rows reduce foliar disease pressure.', '🍇'),
(8, 'Rice', 'Oryza sativa', 'Poaceae', 'rice_blast,rice_bacterial_leaf_streak,rice_brown_spot,rice_healthy', 'Grown under flooded paddy or aerobic upland systems; requires high temperatures and humidity.', '22-34°C', '5.5-6.5', 'Continuous shallow flooding (2-5 cm) or alternate wetting and drying depending on system.', '🌾'),
(9, 'Wheat', 'Triticum aestivum', 'Poaceae', 'wheat_leaf_rust,wheat_powdery_mildew,wheat_septoria,wheat_healthy', 'Cool-season cereal requiring firm seedbed, adequate basal phosphorus, and timely top-dressing.', '15-25°C', '6.0-7.0', 'Critical irrigation stages: crown root initiation, flowering, and grain filling.', '🌾'),
(10, 'Citrus', 'Citrus spp.', 'Rutaceae', 'citrus_greening,citrus_canker,citrus_black_spot,citrus_healthy', 'Subtropical tree needing well-aerated sandy loam, rich micronutrients (Iron, Zinc), and windbreaks.', '20-32°C', '5.5-6.5', 'Water deeply when top 2 inches dry out. Prevent water ponding around root collar.', '🍊'),
(11, 'Rose', 'Rosa spp.', 'Rosaceae', 'rose_black_spot,rose_powdery_mildew,rose_rust,rose_healthy', 'Ornamental woody perennial thriving in rich, compost-amended soil with at least 6 hours of direct sun.', '18-28°C', '6.0-6.5', 'Water at soil level early in the morning. Avoid overhead sprinklers.', '🌹'),
(12, 'Strawberry', 'Fragaria × ananassa', 'Rosaceae', 'strawberry_leaf_scorch,strawberry_angular_leafspot,strawberry_healthy', 'Shallow-rooted perennial needing raised beds, rich compost, pine needle mulch, and clean weed-free beds.', '18-26°C', '5.5-6.5', 'Keep top 2 inches consistently moist; use drip lines under straw/plastic mulch.', '🍓'),
(13, 'Soybean', 'Glycine max', 'Fabaceae', 'soybean_rust,soybean_bacterial_blight,soybean_healthy', 'Legume capable of fixing atmospheric nitrogen; needs warm seedbeds and good soil moisture at pod fill.', '20-30°C', '6.0-6.8', 'Irrigate during pod elongation and seed filling stages to maximize yield.', '🫘'),
(14, 'Coffee', 'Coffea arabica', 'Rubiaceae', 'coffee_leaf_rust,coffee_berry_disease,coffee_healthy', 'Thrives in tropical highlands with volcanic soil, filtered shade, and distinct wet/dry seasons.', '18-24°C', '5.0-6.0', 'High moisture during flowering; slight dry spell needed to induce uniform blossoming.', '☕'),
(15, 'Cucumber', 'Cucumis sativus', 'Cucurbitaceae', 'cucumber_downy_mildew,cucumber_powdery_mildew,cucumber_healthy', 'Fast-growing vining crop requiring warm soil, high organic matter, and vertical trellises.', '22-30°C', '6.0-6.8', 'Frequent, even watering (1 inch per week). Irregular watering causes bitter fruit.', '🥒')
ON DUPLICATE KEY UPDATE name=VALUES(name);

-- Insert Diseases (Crop-Specific and General Stresses)
INSERT INTO diseases (id, disease_key, display_name, crop_id, category, description, symptoms, treatment, prevention, severity_guidance, organic_control, chemical_control, is_general) VALUES
-- Tomato Diseases
(1, 'tomato_early_blight', 'Early Blight (Alternaria solani)', 1, 'FUNGAL', 
'Common fungal pathogen affecting tomato foliage, stems, and fruit, thriving in warm, humid weather.',
'Concentric ring spots ("bullseye" target pattern) on lower leaves, yellow chlorotic halo around lesions, premature leaf drop starting from base.',
'Prune infected lower leaves immediately and dispose away from field. Apply copper or bio-fungicides every 7-10 days.',
'Maintain wide plant spacing (60cm+), stake plants, use drip irrigation, mulch soil base, and practice 3-year crop rotation.',
'LOW: <10% lower foliage affected. MEDIUM: 10-35% canopy affected with stem lesions. HIGH: >35% defoliation affecting fruit.',
'Spray Bacillus subtilis, neem oil extract, or copper octanoate solution.',
'Apply Chlorothalonil, Mancozeb, or Azoxystrobin following label harvest intervals.', 0),

(2, 'tomato_late_blight', 'Late Blight (Phytophthora infestans)', 1, 'FUNGAL',
'Destructive water-mold pathogen capable of destroying entire tomato and potato canopies in days during cool, wet conditions.',
'Water-soaked, dark greasy lesions on leaves and stems, white fungal fuzz on leaf undersides in high humidity, brown firm rot on green fruit.',
'Uproot severely diseased plants immediately in sealed bags. Spray systemic protective fungicides across adjacent rows.',
'Plant certified disease-free transplants, avoid overhead irrigation, destroy volunteer potato/tomato culls, ensure maximum airflow.',
'LOW: Isolated leaf tips showing water-soaked lesions. MEDIUM: Multiple stems and foliage affected. HIGH: Rapid systemic collapse.',
'Apply preventive copper sulfate sprays or potassium phosphite biostimulants.',
'Apply Metalaxyl-M, Dimethomorph, or Mandipropamid systemically.', 0),

(3, 'tomato_yellow_leaf_curl', 'Tomato Yellow Leaf Curl Virus (TYLCV)', 1, 'VIRAL',
'Geminivirus transmitted primarily by the silverleaf whitefly (Bemisia tabaci), causing severe stunting.',
'Upward curling and cupping of leaflet margins, interveinal chlorosis, stunted bushy plant habit, severe floral abortion and failure to set fruit.',
'No cure exists for viral infection. Remove and destroy infected plants immediately to prevent whitefly vector transmission.',
'Install yellow sticky traps, use reflective silver mulches, control whitefly populations, and grow resistant tomato cultivars (Ty-resistant).',
'LOW: Mild leaf curling on top shoot. MEDIUM: Moderate stunting, noticeable leaf chlorosis. HIGH: Severe stunting, total flower drop.',
'Spray insecticidal soap, neem oil (azadirachtin), or Beauveria bassiana for whitefly control.',
'Apply Imidacloprid, Acetamiprid, or Spiromesifen to target vector nymph and adult populations.', 0),

(4, 'tomato_bacterial_spot', 'Bacterial Spot (Xanthomonas spp.)', 1, 'BACTERIAL',
'Bacterial infection causing unsightly necrotic spotting on leaves and scabby raised blemishes on fruit during hot, rainy spells.',
'Small (2-3mm) circular dark brown water-soaked spots with yellow halos on foliage; spots may coalesce causing leaf scorching.',
'Avoid handling or pruning wet plants. Spray copper-based bactericides combined with mancozeb for synergy.',
'Use hot-water treated seeds, sanitize tools with 10% bleach, avoid overhead irrigation, rotate away from solanaceous crops for 2 years.',
'LOW: Sparse spots on lower leaves. MEDIUM: Moderate leaf spotting across canopy. HIGH: Heavy defoliation and fruit pustules.',
'Apply fixed copper hydroxide combined with Bacillus amyloliquefaciens.',
'Apply Copper Hydroxide + Mancozeb tank mix or Streptomycin formulations where permitted.', 0),

(5, 'tomato_healthy', 'Healthy Tomato Plant', 1, 'UNKNOWN',
'Plant displays vigorous, balanced vegetative and reproductive growth with vibrant green foliage.',
'Uniform deep green color, sturdy erect stems, clean flower clusters, and firm blemish-free fruit without chlorosis or necrosis.',
'Maintain current watering, feeding, and pest monitoring routine.',
'Continue balanced N-P-K fertilization, regular pruning of suckers, staking, and proactive pest scouting.',
'LOW: N/A (Optimal plant vitality).',
'Compost tea drenches and beneficial microbial inoculants to support root health.',
'No chemical intervention required.', 0),

-- Potato Diseases
(6, 'potato_early_blight', 'Early Blight (Alternaria solani)', 2, 'FUNGAL',
'Fungal leaf spot reducing photosynthesis and prematurely aging potato vines, reducing tuber yield.',
'Dark brown target-like concentric rings on older leaves, yellowing margins, dry leathery spots.',
'Apply foliar protective fungicides at first sighting. Ensure balanced potassium fertilization to boost resistance.',
'Plant certified seed potatoes, maintain adequate plant spacing, avoid overhead sprinkler irrigation.',
'LOW: Few lower leaves spotted. MEDIUM: 20% vine coverage. HIGH: Extensive vine dieback.',
'Copper hydroxide or Trichoderma harzianum soil and foliar applications.',
'Mancozeb, Difenoconazole, or Boscalid.', 0),

(7, 'potato_late_blight', 'Late Blight (Phytophthora infestans)', 2, 'FUNGAL',
'Historic destructive pathogen that infects foliage, stems, and tubers causing rapid tissue collapse.',
'Pale green water-soaked spots turning dark brown/purplish-black with fuzzy white growth underneath in humid mornings.',
'Destroy infected vines before harvest. Apply protective and curative fungicides immediately across field.',
'Ensure high soil hilling to protect tubers from wash-in spores, destroy cull piles, monitor blight warning forecasts.',
'LOW: Spotting on 1-2 plants. MEDIUM: Spreading across canopy. HIGH: Field-wide collapse.',
'Copper octanoate and bio-fungicides.',
'Cymoxanil + Mancozeb, Fluopicolide, or Propamocarb.', 0),

(8, 'potato_healthy', 'Healthy Potato Canopy', 2, 'UNKNOWN',
'Dense, dark green foliage with sturdy vine structure and healthy root/tuber development.',
'Vibrant green leaves, upright bushy vines, absence of wilting, spots, or pest chewing.',
'Continue optimal irrigation and monitor for Colorado potato beetles.',
'Maintain soil hilling, moderate nitrogen application, and consistent soil moisture.',
'LOW: N/A (Optimal plant vitality).',
'Organic kelp meal and bio-stimulants.',
'No chemicals needed.', 0),

-- Chili / Pepper Diseases
(9, 'pepper_bacterial_spot', 'Bacterial Spot (Xanthomonas campestris)', 3, 'BACTERIAL',
'Common bacterial disease of peppers causing defoliation, sunburned fruit, and reduced yield.',
'Small, water-soaked, dark green spots on foliage turning brown with yellow borders; leaves turn yellow and drop readily.',
'Strip severely infected foliage. Apply copper bactericides. Avoid working in wet fields.',
'Use certified disease-free seed, dip seeds in warm water before sowing, avoid overhead irrigation.',
'LOW: Isolated lower leaf spots. MEDIUM: Moderate defoliation. HIGH: Severe defoliation and fruit drop.',
'Copper soap / Copper octanoate + Bacillus subtilis.',
'Copper Hydroxide + Kasugamycin or Mancozeb.', 0),

(10, 'pepper_anthracnose', 'Anthracnose Fruit & Leaf Spot (Colletotrichum spp.)', 3, 'FUNGAL',
'Fungal disease causing circular sunken lesions on pepper fruit and dark brown lesions on foliage.',
'Water-soaked circular lesions on ripe and immature fruit, becoming sunken with pinkish/orange concentric spore rings in wet weather.',
'Harvest and discard all symptomatic fruit immediately. Spray protective fungicides.',
'Mulch beds to prevent soil splash, rotate crops, practice proper plant spacing for quick canopy drying.',
'LOW: Spots visible on 1-2 fruits. MEDIUM: 15% crop loss with foliar spots. HIGH: Over 40% fruit rot.',
'Neem oil, potassium bicarbonate, or copper fungicides.',
'Azoxystrobin, Pyraclostrobin, or Chlorothalonil.', 0),

(11, 'pepper_healthy', 'Healthy Chili/Pepper Plant', 3, 'UNKNOWN',
'Robust bushy plant with glossy deep green foliage, crisp white flowers, and firm, developing peppers.',
'Vibrant foliage without curling, spotting, or insect damage; strong branch structure.',
'Maintain balanced feeding (moderate N, higher P-K during fruiting) and steady watering.',
'Scout regularly for aphids and thrips; maintain mulch layer to preserve soil moisture.',
'LOW: N/A (Optimal plant vitality).',
'Compost dressings and bio-fertilizers.',
'No chemical intervention needed.', 0),

-- Cotton Diseases
(12, 'cotton_bacterial_blight', 'Bacterial Blight / Angular Leaf Spot (Xanthomonas citri pv. malvacearum)', 4, 'BACTERIAL',
'Bacterial disease affecting all above-ground parts of the cotton plant, prominent in warm, wet climates.',
'Angular dark brown/black water-soaked lesions bounded by leaf veins; can cause "blackarm" stem lesions and boll rot.',
'Destroy crop residues after harvest. Apply copper-based bactericides where field conditions permit.',
'Plant resistant transgenic or hybrid cultivars, acid-delint seed before planting, avoid flood over-irrigation.',
'LOW: Angular spots on lower leaves. MEDIUM: Lesions extending to stems. HIGH: Blackarm girdling and boll rot.',
'Copper oxychloride sprays and plant defense activators.',
'Streptomycin Sulfate or Copper Hydroxide formulations.', 0),

(13, 'cotton_bollworm_damage', 'Bollworm / Helicoverpa Pest Damage', 4, 'PEST',
'Insect pest caterpillar boring into squares, flowers, and bolls, leading to massive yield losses.',
'Chewed holes in flower buds (squares) and bolls with visible caterpillar frass; flared squares and premature boll drop.',
'Handpick caterpillars if small plot. Release Trichogramma parasitoid wasps or apply Bt sprays.',
'Scout twice weekly for eggs on top leaves, grow trap crops (marigold, castor), plant Bt cotton hybrids.',
'LOW: <5% square damage. MEDIUM: 5-15% square damage. HIGH: >15% square/boll infestation.',
'Bacillus thuringiensis (Bt) sprays, Neem oil (Azadirachtin 1500 ppm), Spinosad.',
'Emamectin Benzoate, Chlorantraniliprole, or Flubendiamide.', 0),

(14, 'cotton_healthy', 'Healthy Cotton Field', 4, 'UNKNOWN',
'Vigorous vegetative growth with strong main stem, healthy dark green leaves, and abundant fruiting branches.',
'Erect structure, absence of leaf curling, strong square retention, and clean developing bolls.',
'Maintain balanced nutrition and soil moisture management during peak squaring.',
'Continue integrated pest management (IPM) scouting and pheromone trap monitoring.',
'LOW: N/A (Optimal plant vitality).',
'Organic fish amino acid foliar sprays.',
'No chemicals needed.', 0),

-- Corn / Maize Diseases
(15, 'corn_northern_leaf_blight', 'Northern Corn Leaf Blight (Exserohilum turcicum)', 5, 'FUNGAL',
'Fungal disease causing large elliptical grayish-green or tan lesions that reduce grain fill.',
'Cigar-shaped, elongated tan/gray lesions (2-15 cm long) running parallel to leaf veins, starting on lower leaves.',
'Apply foliar fungicides at tasseling stage if weather is cool (18-27°C) and humid.',
'Plant resistant corn hybrids, shred and till previous crop debris, rotate crops for at least 1 year.',
'LOW: Few lesions on bottom leaves after silking. MEDIUM: Lesions reaching ear leaf. HIGH: Blight covering upper canopy before grain fill.',
'Trichoderma-based biocontrol and copper formulations.',
'Pyraclostrobin + Fluxapyroxad, Propiconazole, or Azoxystrobin.', 0),

(16, 'corn_common_rust', 'Common Rust (Puccinia sorghi)', 5, 'FUNGAL',
'Airborne fungal rust pathogen creating powdery pustules on corn foliage.',
'Cinnamon-brown to brick-red oval or elongated pustules (uredinia) scattered on both upper and lower leaf surfaces.',
'Apply fungicides if rust appears before tasseling on susceptible inbred lines or sweet corn.',
'Select resistant hybrids with Rp gene resistance; early planting to avoid high airborne spore loads.',
'LOW: Scattered pustules on lower leaves. MEDIUM: Pustules on upper leaves. HIGH: Coalescing pustules causing chlorosis and leaf death.',
'Bio-fungicides like Bacillus subtilis or sulfur formulations.',
'Tebuconazole, Propiconazole, or Azoxystrobin.', 0),

(17, 'corn_healthy', 'Healthy Corn Stand', 5, 'UNKNOWN',
'Tall, sturdy stalks with broad emerald-green leaves and vigorous ear/tassel development.',
'Clean dark green leaves with no necrotic streaks; strong adventitious prop roots.',
'Provide side-dress nitrogen during V6 stage and ensure adequate moisture at pollination.',
'Maintain weed-free rows and monitor for fall armyworm.',
'LOW: N/A (Optimal plant vitality).',
'Organic manure tea and mycorrhizal soil inoculants.',
'No chemicals needed.', 0),

-- Apple Diseases
(18, 'apple_scab', 'Apple Scab (Venturia inaequalis)', 6, 'FUNGAL',
'Severe fungal disease of apple trees affecting leaves, blossoms, and fruit.',
'Olive-green to velvety dark brown spots on leaves; fruit develops corky, scabby brown lesions that crack.',
'Rake and destroy fallen leaves in autumn. Spray protective fungicides from bud break through petal fall.',
'Prune trees for open canopy sunlight, choose scab-resistant apple cultivars (e.g., Liberty, Enterprise).',
'LOW: Few spots on foliage. MEDIUM: 20% leaf infection with some fruit scabs. HIGH: Severe defoliation and cracked fruit.',
'Lime sulfur, wettable sulfur, or potassium bicarbonate.',
'Captan, Mancozeb, Difenoconazole, or Cyprodinil.', 0),

(19, 'apple_black_rot', 'Apple Black Rot / Frogeye Leaf Spot (Botryosphaeria obtusa)', 6, 'FUNGAL',
'Fungal disease causing circular leaf spots ("frogeye"), bark cankers, and firm black mummified fruit rot.',
'Small purple specks on leaves expanding into circular spots with tan centers and dark margins; black rotted mummified fruit on tree.',
'Prune out dead wood, fire blight strikes, and remove mummified apples from tree during winter.',
'Maintain tree vigor with balanced fertilizer; paint trunk to prevent winter sunscald cracking.',
'LOW: Few leaf spots. MEDIUM: Cankers on small branches. HIGH: Large trunk cankers and fruit rot.',
'Copper sprays during dormant stage.',
'Captan, Thiophanate-methyl, or Fludioxonil.', 0),

(20, 'apple_healthy', 'Healthy Apple Tree', 6, 'UNKNOWN',
'Lush green canopy with balanced shoot extension and clean developing fruit.',
'Glossy, healthy foliage without curling, spots, or powdery coating.',
'Ensure regular deep watering and maintain organic mulch ring around root drip line.',
'Follow dormant pruning schedule and seasonal pest monitoring.',
'LOW: N/A (Optimal plant vitality).',
'Compost mulch and organic kelp foliar sprays.',
'No chemical intervention needed.', 0),

-- Grape Diseases
(21, 'grape_black_rot', 'Grape Black Rot (Guignardia bidwellii)', 7, 'FUNGAL',
'Devastating fungal disease causing small brown leaf spots and turning grape berries into hard black mummies.',
'Small circular reddish-brown spots on leaves; berries turn pale, soften, turn purple-black, and shrivel into hard mummies.',
'Prune away infected canes and mummified berry clusters. Apply fungicides early in spring.',
'Open canopy via leaf pulling and shoot positioning; ensure excellent airflow through trellis.',
'LOW: Few leaf spots. MEDIUM: 10-25% bunch infection. HIGH: Total berry bunch mummification.',
'Copper hydroxide and sulfur sprays.',
'Myclobutanil, Mancozeb, or Kresoxim-methyl.', 0),

(22, 'grape_powdery_mildew', 'Grape Powdery Mildew (Erysiphe necator)', 7, 'FUNGAL',
'Ubiquitous fungal disease coating leaves, stems, and grapes in a dusty white/gray powdery residue.',
'Powdery white or ash-gray fungal coating on upper leaf surfaces; infected berries become stunted, scarred, and split.',
'Spray horticultural oil or sulfur at early budbreak and through pre-bloom stages.',
'Canopy management to increase sunlight exposure; avoid excessive nitrogen fertilizer which causes lush susceptible growth.',
'LOW: Sparse white patches on few leaves. MEDIUM: Moderate coating on leaves and clusters. HIGH: Heavy mildew causing berry splitting.',
'Potassium bicarbonate, neem oil, sulfur powder, or Bacillus pumilus.',
'Trifloxystrobin, Tebuconazole, or Boscalid.', 0),

(23, 'grape_healthy', 'Healthy Vineyard Grapevine', 7, 'UNKNOWN',
'Clean, vibrant green foliage and well-aerated, uniform fruit clusters.',
'Healthy green fan-shaped leaves, firm cane growth, and uniform berry development.',
'Maintain shoot positioning, suckering, and balanced drip irrigation.',
'Monitor cluster zone air circulation and keep vineyard floor weed-free.',
'LOW: N/A (Optimal plant vitality).',
'Bio-dynamic compost teas and mycorrhizae.',
'No chemicals needed.', 0),

-- Rice Diseases
(24, 'rice_blast', 'Rice Blast (Magnaporthe oryzae)', 8, 'FUNGAL',
'One of the most destructive cereal diseases, attacking leaves, collars, nodes, and panicles.',
'Spindle-shaped / diamond-shaped lesions with grayish centers and brown borders on leaves; neck rot causing blank whiteheads.',
'Maintain water level in paddy fields. Avoid excessive nitrogen fertilizer. Spray tricyclazole at heading.',
'Plant resistant cultivars, use clean seed, practice synchronized planting, avoid drought stress in paddy.',
'LOW: Scattered leaf lesions. MEDIUM: Collar and node infection. HIGH: Neck blast causing whitehead sterility.',
'Pseudomonas fluorescens seed treatment and bio-fungicides.',
'Tricyclazole, Isoprothiolane, or Kasugamycin.', 0),

(25, 'rice_healthy', 'Healthy Rice Paddy', 8, 'UNKNOWN',
'Vigorous tillering, erect dark green leaves, and uniform golden panicle emergence.',
'Clean upright leaves, firm culms, and well-filled grains with no spotting or discoloration.',
'Maintain proper water depth and apply balanced split nitrogen-potassium fertilizers.',
'Scout for brown planthopper and stem borer insects.',
'LOW: N/A (Optimal plant vitality).',
'Azospirillum and blue-green algae bio-fertilizers.',
'No chemicals needed.', 0),

-- Wheat Diseases
(26, 'wheat_leaf_rust', 'Wheat Leaf / Brown Rust (Puccinia triticina)', 9, 'FUNGAL',
'Airborne fungal pathogen producing orange-brown pustules on wheat leaves, reducing grain weight.',
'Small, round-to-oval orange-brown powdery pustules scattered randomly on upper leaf surfaces.',
'Apply foliar triazole or strobilurin fungicides at flag leaf emergence if weather is warm and humid.',
'Grow rust-resistant wheat varieties (with Lr genes), eliminate volunteer wheat seedlings before sowing.',
'LOW: Pustules on lower leaves. MEDIUM: Pustules on sub-flag leaf. HIGH: Flag leaf covered with rust.',
'Bio-formulations of Bacillus subtilis.',
'Propiconazole, Tebuconazole, or Azoxystrobin.', 0),

(27, 'wheat_healthy', 'Healthy Wheat Crop', 9, 'UNKNOWN',
'Uniform stand with upright tillers, broad green flag leaves, and well-developed grain heads.',
'Healthy green canopy, absence of lodging, clean stems, and fully filled spikelets.',
'Provide timely irrigation during crown root initiation, jointing, and grain filling.',
'Monitor soil nutrient levels and scout for aphids or powdery mildew.',
'LOW: N/A (Optimal plant vitality).',
'Organic vermicompost extracts.',
'No chemicals needed.', 0),

-- General Abiotic Stresses (Applicable to All Crops, crop_id = NULL)
(28, 'nitrogen_deficiency_general', 'Nitrogen Deficiency (Abiotic Stress)', NULL, 'ABIOTIC',
'Essential macronutrient shortage causing impaired chlorophyll synthesis and overall stunted vegetative growth.',
'General pale green to yellowish discoloration starting uniformly on older lower leaves; stunted upright growth; thin stems.',
'Apply quick-acting water-soluble nitrogen fertilizer (urea, ammonium nitrate, or fish hydrolysate foliar spray).',
'Conduct regular soil tests, incorporate well-rotted compost or leguminous green manure before planting, use split nitrogen applications.',
'LOW: Mild paling of lowest leaves. MEDIUM: General yellowing of lower third of canopy. HIGH: Severe yellowing and stunted biomass.',
'Foliar spray of fish amino acid, liquid kelp, or blood meal soil amendment.',
'Apply Calcium Nitrate, Urea (46-0-0), or balanced 20-20-20 water-soluble fertilizer.', 1),

(29, 'potassium_deficiency_general', 'Potassium Deficiency (Abiotic Stress)', NULL, 'ABIOTIC',
'Macronutrient deficiency affecting plant water regulation, enzyme activation, and stress resistance.',
'Marginal chlorosis and scorching (browning/necrosis) along the outer edges of older leaves; weak stems; poor fruit quality.',
'Top-dress with potassium sulfate or spray foliar potassium nitrate solution.',
'Maintain balanced N-K ratio in soil, avoid over-application of calcium/magnesium which competes with potassium uptake.',
'LOW: Slight yellowing on leaf margins. MEDIUM: Distinct burnt/scorched leaf edges. HIGH: Extensive leaf edge necrosis and lodging.',
'Wood ash (in moderation), greensand, or kelp meal.',
'Potassium Sulfate (0-0-50) or Potassium Nitrate (13-0-44).', 1),

(30, 'iron_chlorosis_general', 'Iron Deficiency / Interveinal Chlorosis', NULL, 'ABIOTIC',
'Micronutrient disorder common in alkaline or waterlogged soils, hindering chlorophyll production.',
'Striking interveinal chlorosis where leaf veins remain dark green while tissue between veins turns bright yellow to ivory-white, starting on youngest new leaves.',
'Apply chelated iron (Fe-EDDHA for alkaline soils, Fe-EDTA for neutral soils) as a foliar spray or root drench.',
'Lower soil pH with elemental sulfur if above 7.5; improve soil aeration and avoid over-irrigation.',
'LOW: Light interveinal yellowing on new shoots. MEDIUM: Bright yellow new leaves with green veins. HIGH: Ivory-white leaves with necrotic tips.',
'Foliar spray of iron sulfate with citric acid or kelp extract.',
'Chelated Iron (Fe-EDDHA 6% or Fe-DTPA 7%).', 1),

(31, 'water_stress_drought_general', 'Drought / Underwatering Stress', NULL, 'ABIOTIC',
'Severe soil moisture deficit causing loss of turgor pressure and thermal stress in plants.',
'Upward leaf curling, wilting/drooping canopy during midday, dull grayish-green color, dry crispy leaf tips, premature blossom drop.',
'Provide deep, slow soaking irrigation immediately. Mulch soil surface with straw or compost to lock in moisture.',
'Install drip irrigation with timers, apply organic mulch (5-8 cm deep), improve soil organic matter content to boost water retention.',
'LOW: Temporary midday wilt with quick recovery. MEDIUM: Persistent wilt and leaf curling. HIGH: Crispy necrotic leaf edges and shoot dieback.',
'Apply seaweed extract / biostimulants to reduce osmotic shock.',
'Irrigation water + balanced electrolyte/potassium supplements.', 1),

(32, 'waterlogging_stress_general', 'Waterlogging / Overwatering / Root Hypoxia', NULL, 'ABIOTIC',
'Excessive soil saturation depriving plant roots of oxygen, leading to root rot and nutrient uptake failure.',
'Lower leaves turn yellow and drop; soft, limp wilting despite wet soil; foul root odor or darkened brown roots; edema blisters.',
'Immediately halt irrigation; improve drainage channels; aerate heavy compacted soil around root zone.',
'Plant on raised beds or ridges, ensure pots have drainage holes, incorporate perlite or compost into heavy clay soils.',
'LOW: Soil soggy with slight lower yellowing. MEDIUM: Persistent limp foliage and root darkening. HIGH: Root rot and plant collapse.',
'Drench soil with Hydrogen Peroxide (3% diluted 1:10) to introduce oxygen, plus Trichoderma to suppress Pythium.',
'Apply Phosphorous acid (Fosetyl-Al) or Metalaxyl to protect roots from opportunistic water molds.', 1),

(33, 'heat_sunscald_stress_general', 'Heat Stress & Sunscald', NULL, 'ABIOTIC',
'Excessive solar radiation and high ambient temperatures causing cellular damage and bleaching.',
'White, bleached, or papery patches on leaves and sun-exposed fruit; leathery dried spots; leaf margin scorch.',
'Erect temporary 30-50% shade cloth; apply kaolin clay foliar spray to reflect UV radiation; maintain adequate root hydration.',
'Provide afternoon shade for sensitive crops; maintain dense healthy foliar canopy to shade fruit; avoid heavy midsummer pruning.',
'LOW: Superficial bleaching on upper leaves. MEDIUM: Papery sunscald on 20% fruit. HIGH: Severe fruit blistering and canopy burn.',
'Foliar spray of Kaolin clay (Surround WP) and humic acid.',
'Anti-transpirant / solar reflectant sprays.', 1),

(34, 'pest_infestation_general', 'Sucking Pest Damage (Aphids / Mites / Thrips)', NULL, 'PEST',
'Insect pests piercing plant tissues to feed on cellular sap, stunting growth and transmitting viruses.',
'Stippled yellow dots on foliage, fine webbing on leaf undersides, distorted crinkled leaves, sticky honeydew with black sooty mold.',
'Blast foliage with strong water spray; apply insecticidal soap or horticultural neem oil spray directly to leaf undersides.',
'Encourage beneficial predators (ladybugs, lacewings, predatory mites); place yellow and blue sticky traps; avoid excess nitrogen.',
'LOW: Isolated clusters on young shoots. MEDIUM: Widespread stippling and honeydew. HIGH: Severe leaf distortion and sooty mold.',
'Neem oil (Azadirachtin), insecticidal potassium soap, or diatomaceous earth dusting.',
'Acetamiprid, Abamectin, or Spirotetramat.', 1),

(35, 'unknown_stress_general', 'Unidentified Stress / General Advisory Required', NULL, 'UNKNOWN',
'Diagnostic pattern does not match a single specific pathogen with high statistical confidence, indicating multiple overlapping stressors or an uncataloged variety.',
'Ambiguous chlorosis, subtle leaf curling, localized spots or general lack of plant vigor.',
'Conduct standard agronomic triage: inspect soil moisture, test root firmness, check for hidden stem borers or undersides pests.',
'Review watering schedule, check soil pH and EC, avoid over-fertilizing, isolate symptomatic plants, and consult a local agricultural extension officer.',
'LOW: Mild atypical symptoms. MEDIUM: Multiple stress signs visible. HIGH: Progressive decline of unknown origin.',
'Balanced compost tea, organic seaweed extract, and general neem oil preventive spray.',
'Do not apply aggressive chemical treatments without lab diagnosis or expert confirmation.', 1)
ON DUPLICATE KEY UPDATE display_name=VALUES(display_name);

-- Demo User
INSERT INTO users (id, username, email, password_hash, full_name, role) VALUES
(1, 'farmer_john', 'john@agriguard.ai', '$2a$10$7s.P75vUv7E7/0yO02K7u.7QzU7O6N8wG5Y8uV2X5Z8s5U2X5Z8s5', 'John Green', 'ROLE_USER'),
(2, 'admin', 'admin@agriguard.ai', '$2a$10$7s.P75vUv7E7/0yO02K7u.7QzU7O6N8wG5Y8uV2X5Z8s5U2X5Z8s5', 'AgriGuard Admin', 'ROLE_ADMIN')
ON DUPLICATE KEY UPDATE full_name=VALUES(full_name);
